### ISSUE TITLE
Thoughts on .htaccess

### ISSUE THREAD

**Issue by fishnix** [volkerwiegand/serendipity#3]
Hey! Thanks for maintaining this.  I have an issue when trying to use this for local development and thought you might have some insight.  For an existing site, I have a s9y directory on my local disk in `~/mysite`, with the expected directories that have custom 'stuff' in them -- `~/mysite/{uploads, templates, plugins}`.  I have a compose file like this:

```yml
version: '2'

services:
  db:
    image: mysql:5.7
    ports:
      - "33306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: s9y
      MYSQL_USER: s9y
      MYSQL_PASSWORD: s9y
    networks:
      - s9ynet

  s9y:
    depends_on:
      - db
    image: volkerwiegand/serendipity:latest
    ports:
      - "8000:80"
    volumes:
      - ${PWD}/docker/serendipity_config_local.inc.php:/var/www/html/serendipity_config_local.inc.php
      - ${PWD}/.htaccess:/var/www/html/.htaccess
      - ${PWD}/templates:/var/www/html/templates
      - ${PWD}/uploads:/var/www/html/uploads
      - ${PWD}/plugins:/var/www/html/plugins
    restart: always
    environment:
      S9Y_DB_HOST: db:3306
      S9Y_DB_PASSWORD: s9y
      S9Y_DB_PASSWORD: s9y
      SERVER_NAME: mysite.local:8000
      SERVER_ADMIN: foo@bar.com
      LOG_LEVEL: info
    networks:
      - s9ynet
networks:
  s9ynet:
volumes:
    db_data:
```

This way, I can run things locally or inside docker.  The problem is with the .htaccess volume which has serendipity controlled configuration in it like:

```conf
# BEGIN s9y
ErrorDocument 404 /index.php
DirectoryIndex /index.php
php_value session.use_trans_sid 0
php_value register_globals off
Options -MultiViews

RewriteEngine On
RewriteBase /
RewriteRule ^serendipity_admin.php serendipity_admin.php [NC,L,QSA]
RewriteRule ^((archives/([0-9]+)\-[0-9a-z\.\_!;,\+\-\%]+\.html)/?) index.php?/$1 [NC,L,QSA]
RewriteRule ^(authors/([0-9]+)\-[0-9a-z\.\_!;,\+\-\%]+) index.php?/$1 [NC,L,QSA]
RewriteRule ^(feeds/categories/([0-9;]+)\-[0-9a-z\.\_!;,\+\-\%]+\.rss) index.php?/$1 [NC,L,QSA]
RewriteRule ^(feeds/authors/([0-9]+)\-[0-9a-z\.\_!;,\+\-\%]+\.rss) index.php?/$1 [NC,L,QSA]
RewriteRule ^(categories/([0-9;]+)\-[0-9a-z\.\_!;,\+\-\%]+) index.php?/$1 [NC,L,QSA]
RewriteRule ^archives([/A-Za-z0-9]+)\.html index.php?url=/archives/$1.html [NC,L,QSA]
RewriteRule ^([0-9]+)[_\-][0-9a-z_\-]*\.html index.php?url=$1-article.html [L,NC,QSA]
RewriteRule ^feeds/(.*) index.php?url=/feeds/$1 [L,QSA]
RewriteRule ^unsubscribe/(.*)/([0-9]+) index.php?url=/unsubscribe/$1/$2 [L,QSA]
RewriteRule ^approve/(.*)/(.*)/([0-9]+) index.php?url=approve/$1/$2/$3 [L,QSA]
RewriteRule ^delete/(.*)/(.*)/([0-9]+) index.php?url=delete/$1/$2/$3 [L,QSA]
RewriteRule ^(admin|entries)(/.+)?$ index.php?url=admin/ [L,QSA]
RewriteRule ^archive/? index.php?url=/archive [L,QSA]
RewriteRule ^(index|atom[0-9]*|rss|b2rss|b2rdf).(rss|rdf|rss2|xml) rss.php?file=$1&ext=$2
RewriteRule ^(plugin|plugin)/(.*) index.php?url=$1/$2 [L,QSA]
RewriteRule ^search/(.*) index.php?url=/search/$1 [L,QSA]
RewriteRule ^comments/(.*) index.php?url=/comments/$1 [L,QSA]
RewriteRule ^(serendipity\.css|serendipity_admin\.css)$ index.php?url=/$1 [L,QSA]
RewriteRule ^index\.(html?|php.+) index.php?url=index.html [L,QSA]
RewriteRule ^htmlarea/(.*) htmlarea/$1 [L,QSA]
#RewriteCond %{REQUEST_URI} !-U
RewriteRule (.*\.html?) index.php?url=/$1 [L,QSA]

<Files *.tpl.php>
    deny from all
</Files>

<Files *.tpl>
    deny from all
</Files>

<Files *.sql>
    deny from all
</Files>

<Files *.inc.php>
    deny from all
</Files>

<Files *.db>
    deny from all
</Files>

# END s9y
```

but then gets overwritten by the `entrypoint.sh` script:

```
cat >/var/www/html/$s9yUri/.htaccess <<-EOF
	php_value memory_limit ${memLimit:-128}M
	php_value upload_max_filesize ${maxSize}M
	php_value post_max_size ${maxSize}M
EOF
```

I can think of a few ways to work around and/or solve this issue, but they all involve wrapper scripts or changes to the docker image.  Do you have any thoughts?
